### ISSUE TITLE
simple-oidc-provider

### ISSUE THREAD

**Issue by mdbraber** [qlik-oss/dockerfiles#86]
Hi!

I'm trying to build an (internal) lightweight OIDC provider using node-oidc-provider. It seems that simple-oidc-provider (https://hub.docker.com/r/qlik/simple-oidc-provider) has most of what I need. I'd like to fork it and make some changes, but unfortunately the source repo (https://www.github.com/qlik-trial/simple-oidc-provider) is gone. 

@hairyhenderson could you help out / let me know if this repo is available still somewhere?

**Comment by hairyhenderson** [comment]
Hi @mdbraber! Thanks for reaching out.

I'm not totally familiar with the `qlik/simple-oidc-provider` Docker image, but my understanding is that it's public only for convenience - it's not a supported open-source project of ours.

The repo actually does exist, but it's private. I know that there has been some internal discussion over whether or not to open-source it - I'll see if I can find the right people for this!

**Comment by mdbraber** [comment]
@hairyhenderson thanks  for your reply! In the meantime I've been able to get what I needed working with https://github.com/dexidp/dex (with an even smaller memory footprint of 4MB). So I'll go ahead and close this issue for now!
